[phases.setup]
nixPkgs = ["nodejs-22_x", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pnpm install",
  "pip3 install -r server/prediction/requirements.txt"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"
